### ISSUE TITLE
Mature Stag Horn Quest Item Low Drop Rate

### ISSUE THREAD

**Issue by Warglaive** [JunkyBulgaria/ProjectBalnaZZar#5]
**Description:**

https://wotlk.evowow.com/?item=37104
This quest item is used for https://wotlk.evowow.com/?quest=12195 quest, it is completeble, but drop rate is too low, you may want to increase it to normal chance.

**Current behaviour:**

Too low drop rate.

**Steps to reproduce the problem:**

Kill Silvercoat Stag and you will see that drop rate is too low.

**Comment by JunkyBulgaria** [comment]
40% drop as intended
